### ISSUE TITLE
What does the 255 mean here?

### ISSUE THREAD

**Issue by fsantanna** [ceu-arduino/arch-avr#7]
https://github.com/ceu-arduino/arch-avr/blob/1383f12f903910ac17f7facb156be5478f85e177/examples/twi/master/twi-07-read-api2.ceu#L99

**Comment by mnaveenkumar2009** [comment]
255 is the default TWDR value when the interrupt occurs (all bits set +
read bit =1 i.e 127*2+1) .. it's sent when slave sends only an ACK without
setting the data. This occurs when unequal data is requested.

The default address value is also 127 .. we can check this by printing TWAR. TWAR/2 (or TWAR>>1) is the address.

**Comment by mnaveenkumar2009** [comment]
Twar/2 or twar>>1 is the address.

**Comment by fsantanna** [comment]
Don't quite get it. How do you distinguish it from "real data" of 255?

**Comment by mnaveenkumar2009** [comment]
Real data of 255 is not available in my API. If real data is required we
will also get fake 255 on unequal data transfers .. you can verify this by
requesting more from slave by a master.

So the API currently only allows data from 0-254.

**Comment by fsantanna** [comment]
Why? Does Arduino have this limitation? Does it make sense to have this limitation?

**Comment by mnaveenkumar2009** [comment]
Not required since equal data is requested. Code snippet was deleted by this commit - f92184a

**Comment by fsantanna** [comment]
Ok. Are these changes going to the driver as well?

**Comment by mnaveenkumar2009** [comment]
Yes, I had removed the condition in the main driver when this issue was opened and discussed in the chat.
