### ISSUE TITLE
Review this code

### ISSUE THREAD

**Issue by fsantanna** [ceu-arduino/arch-avr#8]
https://github.com/ceu-arduino/arch-avr/blob/cd378064437b57022cc779060befc20096d0a8c4/examples/twi/master/twi-07-read-api2.ceu#L98

**Comment by fsantanna** [comment]
What is the conclusion?

**Comment by mnaveenkumar2009** [comment]
The if conditions aren't needed as the user will not request 0 bytes so the else is not reachable as well so I removed them.

**Comment by mnaveenkumar2009** [comment]
Correction : commit ff89710 fixes the issue
